import type { Effect, FlagValue, GameState, Scenario } from "@/engine/types";
import { money } from "@/engine/finance";

const f = (key: string, s: GameState) => s.flags[key];
const flag = (key: string, value: FlagValue = true): Effect => ({ type: "flag", key, value });
const life = (amount: number): Effect => ({ type: "life", amount });
const checking = (amount: number): Effect => ({ type: "checking", amount });
const schedule = (scenario: string, inDays: number): Effect => ({ type: "schedule", scenario, inDays });

const PHONE_REPAIR = 160;
const card = (s: GameState) => (s.flags.cardBalance as number) ?? 0;
const interest = (balance: number) => Math.round(balance * 0.02 * 100) / 100; // ~24% APR, monthly
const CONCERT = 145;

// Order matters only as a tiebreak for events landing on the same day.
export const scenarios: Scenario[] = [
  {
    id: "payday1",
    title: "Payday",
    category: "income",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { day: 1 },
    amount: (s) => s.income,
    lines: ["Direct deposit from Cornerstone Café.", "First one. It hits different when it's yours."],
    autoEffects: (s) => [checking(s.income)],
    choices: [],
    teacher: {
      concept: "Income",
      objective: "Recognize take-home pay as the starting point for every other decision.",
      discussion: "Before anything else happens, what would you do with $842?",
    },
  },
  {
    id: "mom_phone_bill",
    title: "Phone bill",
    category: "bill",
    app: "messages",
    from: "mom",
    visual: "chat",
    when: { day: 2 },
    lines: ["Proud of you for the first paycheck 🙂", "Don't forget the $80 phone bill is in your name now. Due Friday."],
    choices: [
      { id: "pay", label: "Pay it now", effects: [checking(-80), flag("phonePaidOnTime")], reply: "Look at you. Responsible.", tone: "primary" },
      {
        id: "later", label: "Pay it later", hint: "There's a late fee if you forget", effects: [flag("phoneDeferred"), schedule("phone_bill_late", 6)],
        reply: "Just don't forget. They charge extra when it's late.",
      },
      {
        id: "ask", label: "Ask Mom to cover it", hint: "This month only?", effects: [flag("momCovered"), life(-2), schedule("mom_covered_followup", 7)],
        reply: ["…", "Fine. This one time."],
      },
    ],
    teacher: {
      concept: "Needs vs. wants",
      objective: "Distinguish fixed obligations from discretionary spending.",
      discussion: "Is a phone bill a need or a want? Does it change if the phone is how you get to work?",
    },
  },
  {
    id: "concert",
    title: "Concert tickets",
    category: "social",
    app: "messages",
    from: "maya",
    visual: "chat",
    when: { day: 3 },
    lines: ["CONCERT TICKETS DROPPED", "everyone is going. like everyone", `$${CONCERT}. I'm buying mine rn`],
    choices: [
      { id: "buy", label: "Buy a ticket", hint: `−${money(CONCERT)}`, effects: [checking(-CONCERT), life(10), flag("concert", "full"), schedule("concert_night", 19)], reply: ["YESSS", "ok this is going to be the best night"], tone: "primary" },
      { id: "cheaper", label: "Find a cheaper seat", hint: "Lawn seats, $60", effects: [checking(-60), life(5), flag("concert", "lawn"), schedule("concert_night", 19)], reply: ["lawn seats are honestly fine", "we'll find you"] },
      { id: "skip", label: "Skip it", effects: [life(-6), flag("concert", "skip"), schedule("concert_night", 19)], reply: ["oh", "ok 😔 next time"] },
    ],
    teacher: {
      concept: "Opportunity cost",
      objective: "Recognize that spending on one thing removes the option to spend on something later.",
      discussion: "Nobody knows their phone is about to break. How should that change a decision like this one?",
    },
    reflection: "What did buying (or skipping) the ticket cost you later in the month?",
  },
  {
    id: "sneaker_drop",
    title: "Limited drop",
    category: "shopping",
    app: "shop",
    from: "shop",
    visual: "shop",
    when: { day: 4 },
    amount: 89,
    timePressure: 20,
    defaultChoice: "pass",
    lines: ["Court Low ‘Ash’ — limited restock", "Only 40 pairs. Today only. Don't sleep on this one."],
    choices: [
      { id: "buy", label: "Buy now", hint: "−$89", effects: [checking(-89), life(4), flag("sneakers")], tone: "primary" },
      { id: "pass", label: "Let it go", effects: [flag("sneakersPassed")] },
    ],
    teacher: {
      concept: "Impulse spending",
      objective: "Notice how scarcity and countdowns push decisions faster than thinking.",
      discussion: "What did the 20-second timer do to your thinking? Who benefits from the timer?",
    },
  },
  {
    id: "streaming_renewal",
    title: "Streamly renewed",
    category: "subscription",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { day: 5 },
    condition: (s) => s.recurring.some((r) => r.id === "streamly"),
    amount: -18.99,
    lines: ["Card charged: Streamly · $18.99", "Renews monthly. Open Bills to see everything that auto-charges."],
    autoEffects: [checking(-18.99)],
    choices: [
      { id: "keep", label: "Keep it", effects: [] },
      { id: "cancel", label: "Cancel Streamly", hint: "No more monthly charge", effects: [{ type: "recurring", op: "remove", id: "streamly" }, flag("cancelled_streamly"), life(-2)] },
    ],
    teacher: {
      concept: "Recurring expenses",
      objective: "Identify subscriptions as money that leaves before you decide anything.",
      discussion: "How many things auto-charge you or your family right now? Do you know the total?",
    },
  },
  {
    id: "lunch_reload",
    title: "Lunch account",
    category: "bill",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { day: 6 },
    amount: -45,
    lines: (s) => ["Card charged: School lunch account · $45.00", s.seen.filter((x) => x === "lunch_reload").length > 1 ? "Second reload this month. It adds up." : "Auto-reloads when the balance runs low. It's on your card now, not Mom's."],
    autoEffects: (s) => (s.seen.filter((x) => x === "lunch_reload").length > 1 ? [checking(-45)] : [checking(-45), schedule("lunch_reload", 14)]),
    choices: [],
    teacher: {
      concept: "Fixed costs",
      objective: "Recognize costs that arrive automatically and must be planned around.",
      discussion: "Some charges you choose. Some just happen. Which kind is easier to forget?",
    },
  },
  {
    id: "food_run",
    title: "Food after practice",
    category: "social",
    app: "messages",
    from: "jordan",
    visual: "chat",
    when: { day: 6 },
    lines: (s) => ["food after practice?", `it's like $${f("food1", s) ?? 14}. everyone's going`],
    autoEffects: (s, rng) => [flag("food1", rng.int(12, 18))],
    choices: [
      { id: "go", label: "I'm in", effects: (s) => [checking(-(f("food1", s) as number)), life(2), flag("foodOut", 1)], reply: "🙌", tone: "primary" },
      { id: "home", label: "Eating at home tonight", effects: [life(-1)], reply: "ok next time" },
    ],
    teacher: {
      concept: "Small spending",
      objective: "See how small, frequent purchases add up across a month.",
      discussion: "$14 feels like nothing. How much is that over a month of practices?",
    },
  },
  {
    id: "savings_nudge",
    title: "Auto-save",
    category: "saving",
    app: "savings",
    from: "bank",
    visual: "alert",
    when: { day: 7 },
    lines: ["You have $100 in savings.", "Want to move some of each paycheck automatically? You won't miss what you don't see."],
    choices: [
      { id: "auto", label: "Auto-save $50 every payday", effects: [flag("autosave", 50)], tone: "primary" },
      { id: "now", label: "Move $100 now", hint: "Checking → Savings", effects: [{ type: "transfer", from: "checking", to: "savings", amount: 100 }, flag("movedSavings")] },
      { id: "not", label: "Not right now", effects: [flag("noSave")] },
    ],
    teacher: {
      concept: "Emergency fund",
      objective: "Understand saving as protection against surprises, not just delayed spending.",
      discussion: "What's the difference between money in checking and money in savings if it's all yours?",
    },
  },
  {
    id: "extra_shift",
    title: "Extra shift",
    category: "work",
    app: "work",
    from: "alex",
    visual: "work",
    when: { day: 8 },
    lines: ["Hey — someone called out for Saturday.", "Want the shift? It'd be about $96 extra on your next check."],
    choices: [
      { id: "take", label: "I'll take it", effects: [{ type: "income", amount: 96 }, life(-4), flag("extraShift")], reply: "You're a lifesaver. See you Saturday.", tone: "primary" },
      { id: "pass", label: "Can't this weekend", effects: [life(2)], reply: "No worries. I'll ask around." },
    ],
    teacher: {
      concept: "Income vs. time",
      objective: "Weigh extra income against time, energy, and social life.",
      discussion: "Is more money always the right answer? What did the shift cost besides Saturday?",
    },
  },
  {
    id: "friend_borrow",
    title: "Jordan needs $40",
    category: "lending",
    app: "messages",
    from: "jordan",
    visual: "chat",
    when: { day: 9 },
    lines: ["ok weird question", "can I borrow $40 till next week? my card got declined at the store 😭", "I'll pay you back friday promise"],
    choices: [
      {
        id: "lend", label: "Send $40", effects: (s, rng) => [checking(-40), life(2), flag("lent", 40), schedule(rng.next() < 0.6 ? "friend_repays" : "friend_ghosts", 7)],
        reply: "you're the best. seriously.", tone: "primary",
      },
      { id: "half", label: "I can do $20", effects: (s, rng) => [checking(-20), life(1), flag("lent", 20), schedule(rng.next() < 0.6 ? "friend_repays" : "friend_ghosts", 7)], reply: "ok that helps. thank you" },
      { id: "no", label: "I can't right now", effects: [life(-3), flag("refusedLoan")], reply: ["oh", "yeah no it's fine"] },
    ],
    teacher: {
      concept: "Lending",
      objective: "Recognize that a loan to a friend is a gift until it's repaid.",
      discussion: "If you lend $40 and never see it again, was it still the right call? What would you say to Jordan?",
    },
  },
  {
    id: "bnpl_headphones",
    title: "Pay in 4",
    category: "credit",
    app: "shop",
    from: "shop",
    visual: "shop",
    when: { day: 10 },
    amount: 140,
    lines: ["Pulse ANC headphones — $140", "Or 4 payments of $35. 0% interest.* Late payments incur a $7 fee."],
    choices: [
      { id: "full", label: "Pay $140 now", effects: [checking(-140), life(3), flag("headphones", "full")] },
      {
        id: "bnpl", label: "4 payments of $35", hint: "$35 today, $105 owed", tone: "primary",
        effects: [checking(-35), { type: "debt", amount: 105 }, life(3), flag("headphones", "bnpl"), flag("usedBNPL"), schedule("bnpl_payment", 7), schedule("bnpl_payment", 14), schedule("bnpl_payment", 21)],
      },
      { id: "skip", label: "Not today", effects: [flag("headphones", "skip")] },
    ],
    teacher: {
      concept: "Buy now, pay later",
      objective: "Understand that splitting a payment creates debt and future obligations.",
      discussion: "0% interest sounds free. What did the $7 late fee do to that math for anyone who ran low?",
    },
  },
  {
    id: "scam_dm",
    title: "Unknown message",
    category: "scam",
    app: "messages",
    from: "unknown",
    visual: "chat",
    when: { day: 11 },
    autoEffects: (s, rng) => [flag("scamKind", rng.pick(["crypto", "bank"]))],
    lines: (s) =>
      f("scamKind", s) === "bank"
        ? ["NORTHLAKE ALERT: Your account has been LOCKED due to suspicious activity.", "Verify now to restore access: northlake-secure-verify.co/unlock", "Reply with your card number and PIN to skip the wait."]
        : ["hey!! saw you on Maya's story 👋", "I turned $50 into $500 last week flipping crypto. 100% legit, I can show you", "send $50 and I'll send back $100 by friday 💯"],
    choices: [
      {
        id: "send", label: "Reply", hint: "Send the money / details", tone: "risky",
        effects: (s) => (s.flags.scamKind === "bank" ? [flag("scammed"), schedule("scam_fallout", 2)] : [checking(-50), flag("scammed"), schedule("scam_fallout", 3)]),
        reply: (s) => (s.flags.scamKind === "bank" ? "Thank you. Your account will be restored within 24 hours." : ["got it 🙏", "sending friday!!"]),
      },
      { id: "ignore", label: "Ignore", effects: [flag("scamIgnored")] },
      { id: "report", label: "Report & block", effects: [flag("scamReported"), life(1)], tone: "primary" },
    ],
    teacher: {
      concept: "Scams",
      objective: "Spot urgency, guaranteed returns, and requests for card details as scam signals.",
      discussion: "What in the message was designed to make you act fast? Would a real bank ever ask for your PIN?",
    },
    reflection: "Which words in the message were the warning signs?",
  },
  {
    id: "forgotten_sub",
    title: "CloudSave+ charged",
    category: "subscription",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { day: 12 },
    condition: (s) => s.recurring.some((r) => r.id === "cloudsave"),
    amount: -4.99,
    lines: ["Card charged: CloudSave+ · $4.99", "A free trial you started 3 months ago. It's been charging you since."],
    autoEffects: [checking(-4.99)],
    choices: [
      { id: "cancel", label: "Cancel CloudSave+", effects: [{ type: "recurring", op: "remove", id: "cloudsave" }, flag("cancelled_cloudsave")], tone: "primary" },
      { id: "keep", label: "Keep it", effects: [] },
    ],
    teacher: {
      concept: "Free trials",
      objective: "Recognize that free trials convert into recurring charges automatically.",
      discussion: "Why do companies offer free trials? Who is the trial really for?",
    },
  },
  {
    id: "hours_cut",
    title: "Hours cut",
    category: "work",
    app: "work",
    from: "alex",
    visual: "work",
    when: { day: 12 },
    chance: 0.6,
    condition: (s) => !s.flags.extraShift,
    lines: ["Heads up — it's been slow, so I have to trim hours next week.", "Your next check will be about $130 lighter. Sorry, I know the timing's not great."],
    autoEffects: [{ type: "income", amount: -130 }, flag("hoursCut")],
    choices: [{ id: "ok", label: "Understood", effects: [] }],
    teacher: {
      concept: "Income isn't guaranteed",
      objective: "Understand that hourly income can change without warning.",
      discussion: "Some players got a bonus, some got hours cut. How should a plan handle both?",
    },
  },
  {
    id: "phone_repair",
    title: "Cracked screen",
    category: "emergency",
    app: "bank",
    from: "bank",
    visual: "alert",
    when: { day: 14 },
    amount: -PHONE_REPAIR,
    lines: (s) => [
      "Your phone hit the pavement. The screen is shattered — you can barely read this.",
      `Repair: ${money(PHONE_REPAIR)}. You have ${money(s.checking)} in checking and ${money(s.savings)} in savings.`,
    ],
    choices: [
      {
        id: "checking", label: "Pay from checking", effects: [checking(-PHONE_REPAIR), flag("repair", "checking")],
        requires: (s) => (s.checking >= PHONE_REPAIR ? null : `Only ${money(s.checking)} in checking`),
      },
      {
        id: "savings", label: "Use savings", hint: "That's what it's for", effects: [{ type: "savings", amount: -PHONE_REPAIR }, flag("repair", "savings")],
        requires: (s) => (s.savings >= PHONE_REPAIR ? null : `Only ${money(s.savings)} saved`),
      },
      {
        id: "credit", label: "Put it on a credit card", hint: "Pay it back later, with interest", tone: "risky",
        effects: [{ type: "debt", amount: PHONE_REPAIR }, flag("repair", "credit"), flag("usedCredit"), flag("cardBalance", PHONE_REPAIR), schedule("credit_bill", 13)],
      },
      { id: "wait", label: "Live with the cracks for now", hint: "Risky", tone: "risky", effects: [life(-8), flag("repair", "wait"), schedule("phone_dies", 7)] },
    ],
    teacher: {
      concept: "Emergency savings",
      objective: "Experience how earlier choices determine which options exist during a surprise.",
      discussion: "Why did the exact same $160 emergency hurt some players so much more than others?",
    },
    reflection: "Which of your earlier choices decided what options you had here?",
  },
  {
    id: "payday2",
    title: "Payday",
    category: "income",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { day: 15 },
    amount: (s) => s.income,
    lines: (s) => [
      `Direct deposit from Cornerstone Café.${s.flags.extraShift ? " Includes your Saturday shift." : s.flags.hoursCut ? " Reduced hours this period." : ""}`,
      s.flags.autosave ? `Auto-save moved ${money(s.flags.autosave as number)} to savings.` : "Halfway through the month.",
    ],
    autoEffects: (s) => [checking(s.income), ...(s.flags.autosave ? [{ type: "transfer", from: "checking", to: "savings", amount: s.flags.autosave as number } as Effect] : [])],
    choices: [],
    teacher: {
      concept: "Budgeting",
      objective: "Compare the second paycheck to what's already committed for the rest of the month.",
      discussion: "What's already spoken for out of this check before you've decided anything?",
    },
  },
  {
    id: "transport",
    title: "Bike tire",
    category: "transport",
    app: "messages",
    from: "mom",
    visual: "chat",
    when: { day: 17 },
    lines: ["Your bike tire is flat again. I can't drive you this week, I have early shifts.", "How are you getting to work?"],
    choices: [
      { id: "fix", label: "Fix the tire", hint: "−$35, done", effects: [checking(-35), flag("transport", "fix")], reply: "Good. Take care of your stuff and it takes care of you.", tone: "primary" },
      { id: "rides", label: "Rideshare to work", hint: "$12 a ride, a few rides", effects: [checking(-12), flag("transport", "rides"), schedule("ride_charge", 2), schedule("ride_charge", 4)], reply: "That adds up fast, just so you know." },
      { id: "walk", label: "Walk", hint: "45 minutes each way", effects: [life(-6), flag("transport", "walk"), schedule("late_to_work", 2)], reply: "It's far. Leave early." },
    ],
    teacher: {
      concept: "Tradeoffs",
      objective: "Compare one-time fixes against repeated small costs.",
      discussion: "Cheapest today wasn't always cheapest by the end of the month. Where did that show up?",
    },
  },
  {
    id: "sneaker_restock",
    title: "Price drop",
    category: "shopping",
    app: "feed",
    from: "feed",
    visual: "feed",
    when: { day: 18 },
    condition: (s) => !!s.flags.sneakers || !!s.flags.sneakersPassed,
    amount: 59,
    lines: (s) =>
      s.flags.sneakers
        ? ["Court Low ‘Ash’ restocked — now $59.", "\"Limited\" apparently meant two weeks. 2.1k likes."]
        : ["Court Low ‘Ash’ restocked — now $59.", "Same shoes. $30 less. No timer this time."],
    choices: [
      { id: "buy", label: "Buy at $59", effects: [checking(-59), life(4), flag("sneakers")], requires: (s) => (s.flags.sneakers ? "You already own them" : null) },
      { id: "pass", label: "Still no", effects: [] },
    ],
    teacher: {
      concept: "Artificial scarcity",
      objective: "Recognize 'limited' and 'today only' as sales tactics, not facts.",
      discussion: "If the sneakers were always going to restock cheaper, what was the $30 really paying for?",
    },
  },
  {
    id: "food_run_2",
    title: "Boba run",
    category: "social",
    app: "messages",
    from: "maya",
    visual: "chat",
    when: { day: 19 },
    lines: (s) => ["boba after school??", `$${f("food2", s) ?? 9} and I'm buying next time I swear`],
    autoEffects: (s, rng) => [flag("food2", rng.int(7, 11))],
    choices: [
      { id: "go", label: "Yes obviously", effects: (s) => [checking(-(f("food2", s) as number)), life(2), flag("foodOut", ((f("foodOut", s) as number) ?? 0) + 1)], reply: "🧋🧋", tone: "primary" },
      { id: "no", label: "Not today", effects: [life(-1)], reply: "fineee" },
    ],
    teacher: {
      concept: "Small spending",
      objective: "Connect repeated small purchases to the month-end total.",
      discussion: "Which felt worse: saying no to boba, or being short later? Why?",
    },
  },
  {
    id: "family_contribution",
    title: "Your share",
    category: "family",
    app: "messages",
    from: "mom",
    visual: "chat",
    when: { day: 13 },
    lines: ["Reminder that your share of wifi and groceries is $180 this month, like we talked about.", "Whenever you can this week."],
    choices: [
      { id: "pay", label: "Pay $180", effects: [checking(-180), flag("family", "paid")], reply: "Thank you. It really helps.", tone: "primary", requires: (s) => (s.checking >= 180 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "half", label: "$90 now, $90 next payday", effects: [checking(-90), flag("family", "half"), schedule("family_second_half", 14)], reply: "That works. Just don't forget the rest.", requires: (s) => (s.checking >= 90 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "cant", label: "I'm short this month", effects: [life(-5), flag("family", "short")], reply: ["…", "We'll talk about it tonight."] },
    ],
    teacher: {
      concept: "Needs vs. wants",
      objective: "Prioritize obligations to others over discretionary spending.",
      discussion: "Fun purchases happened before this bill came. Should the order have been different?",
    },
  },
  {
    id: "trip_deposit",
    title: "Trip deposit",
    category: "family",
    app: "messages",
    from: "mom",
    visual: "chat",
    when: { day: 23 },
    lines: ["The DC trip deposit is due Friday. $120.", "You said you'd cover it from work money — still good?"],
    choices: [
      { id: "pay", label: "Pay the $120", effects: [checking(-120), life(4), flag("trip", "paid")], reply: "Great. You're going to love it.", tone: "primary", requires: (s) => (s.checking >= 120 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "half", label: "Can you cover half?", effects: [checking(-60), life(2), flag("trip", "half")], reply: ["I can do half.", "But that's the deal then — no more asks this month."], requires: (s) => (s.checking >= 60 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "skip", label: "I'll sit this one out", effects: [life(-8), flag("trip", "skip")], reply: ["Oh.", "Ok. Your call."] },
    ],
    teacher: {
      concept: "Planned expenses",
      objective: "Distinguish expenses you knew were coming from ones you didn't.",
      discussion: "This one was on the calendar the whole month. Did it feel like a surprise anyway? Why?",
    },
  },
  {
    id: "small_surprise",
    title: "Surprise",
    category: "emergency",
    app: "bank",
    from: "bank",
    visual: "bank",
    when: { between: [24, 27] },
    chance: 0.75,
    autoEffects: (s, rng) => {
      const kind = rng.pick(["dentist", "earbuds", "refund"]);
      return [flag("surprise", kind), checking(kind === "dentist" ? -60 : kind === "earbuds" ? -45 : 12.5)];
    },
    amount: (s) => (s.flags.surprise === "dentist" ? -60 : s.flags.surprise === "earbuds" ? -45 : 12.5),
    lines: (s) =>
      s.flags.surprise === "dentist"
        ? ["Card charged: Riverside Dental · $60.00", "Copay for the filling. Insurance covered the rest."]
        : s.flags.surprise === "earbuds"
        ? ["Card charged: Dropp · $45.00", "Replacement earbuds. The old ones went through the wash."]
        : ["Refund: Streamly · +$12.50", "They overcharged you last month and fixed it. Nice when that happens."],
    choices: [{ id: "ok", label: "OK", effects: [] }],
    teacher: {
      concept: "Unexpected costs",
      objective: "Recognize that small surprises are normal, not rare.",
      discussion: "Not every surprise is a broken phone. How much room do you leave for the small ones?",
    },
  },
  {
    id: "bonus",
    title: "Bonus",
    category: "income",
    app: "work",
    from: "alex",
    visual: "work",
    when: { day: 25 },
    condition: (s) => !!s.flags.extraShift && !s.flags.lateToWork,
    lines: ["Covering that Saturday saved us. I put a $75 bonus on your next check — it just posted.", "Keep it up."],
    autoEffects: [checking(75), flag("bonus")],
    choices: [{ id: "thanks", label: "Thank you!", effects: [], reply: "You earned it." }],
    teacher: {
      concept: "Reliability pays",
      objective: "Connect work reliability to income opportunities.",
      discussion: "Only players who took the shift and showed up on time got this. Was it worth the Saturday?",
    },
  },
  {
    id: "end_of_month",
    title: "End of month",
    category: "outcome",
    app: "bank",
    from: "bank",
    visual: "alert",
    when: { day: 30 },
    ends: true,
    lines: ["Month one is in the books.", "Let's see what kind of month you built."],
    choices: [],
    teacher: {
      concept: "Reflection",
      objective: "Compare outcomes across different strategies without declaring a single winner.",
      discussion: "Two players ended with the same checking balance but very different months. Which month would you rather have lived?",
    },
  },

  // ---- Scheduled-only consequences (no `when`; they enter the queue via effects) ----
  {
    id: "phone_bill_late",
    title: "Phone bill overdue",
    category: "bill",
    app: "bills",
    from: "bank",
    visual: "bank",
    amount: -90,
    lines: ["Your phone bill is past due. $80 plus a $10 late fee has been charged.", "Late payments can be reported to credit bureaus."],
    autoEffects: [checking(-90), { type: "credit", amount: -12 }, flag("phoneLate")],
    choices: [{ id: "ok", label: "Got it", effects: [] }],
    teacher: {
      concept: "Late fees & credit",
      objective: "See how deferring a bill costs money and credit health.",
      discussion: "'Later' cost $10 and 12 credit points. What was gained by waiting?",
    },
  },
  {
    id: "mom_covered_followup",
    title: "Mom",
    category: "family",
    app: "messages",
    from: "mom",
    visual: "chat",
    lines: ["I paid the phone bill. I'm not doing that again, ok? It's yours now.", "Love you. Figure it out."],
    autoEffects: [life(-2)],
    choices: [{ id: "ok", label: "I know. Thank you.", effects: [], reply: "❤️" }],
    teacher: {
      concept: "Responsibility",
      objective: "Recognize the social cost of relying on others for obligations.",
      discussion: "Asking for help isn't wrong. When does it become a habit?",
    },
  },
  {
    id: "concert_night",
    title: "Concert night",
    category: "social",
    app: "feed",
    from: "feed",
    visual: "feed",
    lines: (s) =>
      s.flags.concert === "skip"
        ? ["Maya posted 14 stories. Jordan's on someone's shoulders.", "You watched all of them from your room."]
        : s.flags.concert === "lawn"
        ? ["You were far from the stage but Maya found you by the second song.", "Honestly? Same night, $85 cheaper."]
        : ["Front section. Maya screaming next to you. You'll remember this one.", "Worth it — as long as nothing else goes wrong this month."],
    autoEffects: (s) => (s.flags.concert === "skip" ? [life(-4), flag("concertFomo")] : [life(s.flags.concert === "lawn" ? 4 : 5)]),
    choices: [{ id: "ok", label: "Continue", effects: [] }],
    teacher: {
      concept: "Opportunity cost",
      objective: "Compare the emotional payoff of spending to its financial impact.",
      discussion: "Lawn seats got most of the fun for less than half the price. Does 'cheaper option' get used enough in real life?",
    },
  },
  {
    id: "friend_repays",
    title: "Jordan pays you back",
    category: "lending",
    app: "messages",
    from: "jordan",
    visual: "chat",
    lines: (s) => [`sent you the $${s.flags.lent} back!!`, "thank you for real. you saved me"],
    autoEffects: (s) => [checking(s.flags.lent as number), life(3), flag("repaid")],
    choices: [{ id: "ok", label: "Anytime", effects: [], reply: "🫶" }],
    teacher: {
      concept: "Trust",
      objective: "Understand lending as a relationship decision as much as a money one.",
      discussion: "Jordan paid some players back and not others — same friend, same $40. What does that tell you about lending?",
    },
  },
  {
    id: "friend_ghosts",
    title: "About that $40",
    category: "lending",
    app: "messages",
    from: "jordan",
    visual: "chat",
    lines: ["hey so about the money", "can I get it to you next month? things are kind of a mess rn", "sorry 😞"],
    choices: [
      { id: "fine", label: "Don't worry about it", effects: [life(2), flag("forgaveLoan")], reply: "you're actually the best" },
      { id: "need", label: "I kind of need it back", effects: [life(-3), flag("pressedLoan")], reply: ["yeah", "I get it. I'll try"] },
    ],
    teacher: {
      concept: "Trust",
      objective: "Understand lending as a relationship decision as much as a money one.",
      discussion: "Jordan paid some players back and not others — same friend, same $40. What does that tell you about lending?",
    },
  },
  {
    id: "bnpl_payment",
    title: "Pay-in-4 installment",
    category: "credit",
    app: "bills",
    from: "bank",
    visual: "bank",
    amount: -35,
    lines: (s) =>
      s.flags.bnplLastLate
        ? ["Installment auto-charge FAILED — not enough in checking.", "$7 late fee added. This may affect your credit."]
        : [`Installment ${s.flags.bnplPaid} of 4 auto-charged: $35.`, `${4 - (s.flags.bnplPaid as number)} more to go.`],
    autoEffects: (s) =>
      s.checking >= 35
        ? [checking(-35), { type: "debt", amount: -35 }, { type: "credit", amount: 2 }, flag("bnplLastLate", false), flag("bnplPaid", ((s.flags.bnplPaid as number) ?? 1) + 1)]
        : [{ type: "debt", amount: 7 }, { type: "credit", amount: -10 }, flag("bnplLate"), flag("bnplLastLate", true)],
    choices: [{ id: "ok", label: "OK", effects: [] }],
    teacher: {
      concept: "Debt payments",
      objective: "Experience how future payments compete with future needs.",
      discussion: "The $35 came out whether or not you had it. What else did it push out of the way?",
    },
  },
  {
    id: "scam_fallout",
    title: "Account not found",
    category: "scam",
    app: "messages",
    from: "unknown",
    visual: "chat",
    lines: (s) => (s.flags.scamKind === "bank" ? ["Three unknown charges just hit your card. Northlake froze it and issued a new one.", "The 'verification' link wasn't the bank."] : ["This account no longer exists.", "The $50 isn't coming back. Neither is the $100."]),
    autoEffects: (s) => (s.flags.scamKind === "bank" ? [checking(-64.5), life(-6), flag("scamLoss", 64.5)] : [life(-6), flag("scamLoss", 50)]),
    choices: [{ id: "ok", label: "…", effects: [] }],
    teacher: {
      concept: "Scams",
      objective: "See the delayed cost of a rushed trust decision.",
      discussion: "What could you have checked in 30 seconds that would have saved this?",
    },
  },
  {
    id: "phone_dies",
    title: "Screen dead",
    category: "emergency",
    app: "bank",
    from: "bank",
    visual: "alert",
    amount: -210,
    lines: (s) => ["The cracked screen finally stopped responding. You missed two shift messages from Alex.", `Repair is now ${money(210)} because the digitizer went too. You have ${money(s.checking)} in checking, ${money(s.savings)} saved.`],
    choices: [
      { id: "checking", label: "Pay from checking", effects: [checking(-210), flag("repair", "checking-late")], requires: (s) => (s.checking >= 210 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "savings", label: "Use savings", effects: [{ type: "savings", amount: -210 }, flag("repair", "savings-late")], requires: (s) => (s.savings >= 210 ? null : `Only ${money(s.savings)} saved`) },
      { id: "credit", label: "Credit card", tone: "risky", effects: [{ type: "debt", amount: 210 }, flag("repair", "credit-late"), flag("usedCredit"), flag("cardBalance", 210), schedule("credit_bill", 6)] },
    ],
    autoEffects: [life(-4), flag("lateToWork")],
    teacher: {
      concept: "Delaying costs",
      objective: "See how postponing a necessary expense often makes it larger.",
      discussion: "Waiting turned $160 into $210 and cost a bonus. When is waiting the smart move, and when isn't it?",
    },
  },
  {
    id: "credit_bill",
    title: "Credit card statement",
    category: "credit",
    app: "bills",
    from: "bank",
    visual: "bank",
    amount: (s) => -card(s),
    lines: (s) => [`Statement balance: ${money(card(s))}. Minimum due: $25.`, "Pay in full to avoid 24% interest on the rest."],
    choices: [
      { id: "full", label: "Pay in full", effects: (s) => [checking(-card(s)), { type: "debt", amount: -card(s) }, { type: "credit", amount: 8 }, flag("cardBalance", 0), flag("creditPaidFull")], requires: (s) => (s.checking >= card(s) ? null : `Only ${money(s.checking)} in checking`), tone: "primary" },
      { id: "min", label: "Pay the $25 minimum", hint: "Interest starts on the rest", effects: (s) => [checking(-25), { type: "debt", amount: -25 + interest(card(s) - 25) }, { type: "credit", amount: -3 }, flag("cardBalance", card(s) - 25 + interest(card(s) - 25)), flag("creditMinimum")], requires: (s) => (s.checking >= 25 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "skip", label: "Skip this month", tone: "risky", effects: (s) => [{ type: "debt", amount: 29 + interest(card(s)) }, { type: "credit", amount: -25 }, flag("cardBalance", card(s) + 29 + interest(card(s))), flag("creditMissed")] },
    ],
    teacher: {
      concept: "Credit & interest",
      objective: "Understand minimum payments as a way debt grows instead of shrinking.",
      discussion: "The minimum payment felt easier. What happens to the balance if you only ever pay the minimum?",
    },
  },
  {
    id: "ride_charge",
    title: "Rideshare",
    category: "transport",
    app: "bank",
    from: "bank",
    visual: "bank",
    amount: -12,
    lines: ["Card charged: GoRide · $12.00", "Another ride to work."],
    autoEffects: [checking(-12)],
    choices: [{ id: "ok", label: "OK", effects: [] }],
    teacher: {
      concept: "Repeated costs",
      objective: "Compare small repeated costs to a one-time fix.",
      discussion: "Three rides cost more than fixing the tire. Why does paying $12 still feel easier than paying $35?",
    },
  },
  {
    id: "late_to_work",
    title: "Late",
    category: "work",
    app: "work",
    from: "alex",
    visual: "work",
    lines: ["You were 20 minutes late twice this week.", "I get that the bike is broken, but I need you here on time."],
    autoEffects: [life(-3), flag("lateToWork")],
    choices: [{ id: "ok", label: "I'm sorry. I'll fix it.", effects: [], reply: "Thanks. I know you will." }],
    teacher: {
      concept: "Hidden costs",
      objective: "Recognize non-money costs of 'free' options.",
      discussion: "Walking was free. Was it?",
    },
  },
  {
    id: "family_second_half",
    title: "The other $90",
    category: "family",
    app: "messages",
    from: "mom",
    visual: "chat",
    lines: ["Hey — the other $90 for wifi and groceries?"],
    choices: [
      { id: "pay", label: "Sending it now", effects: [checking(-90), flag("family", "paid-late")], reply: "Thank you 🙂", tone: "primary", requires: (s) => (s.checking >= 90 ? null : `Only ${money(s.checking)} in checking`) },
      { id: "cant", label: "I don't have it", effects: [life(-5), flag("family", "short")], reply: "Ok. We'll figure it out." },
    ],
    teacher: {
      concept: "Commitments",
      objective: "See how split payments become future obligations that compete with new wants.",
      discussion: "Splitting the payment felt easier on day 20. How did it feel on day 28?",
    },
  },
];


export const scenarioById = Object.fromEntries(scenarios.map((s) => [s.id, s]));
